navbar:
  title:
    text: :vn(title):V&N Team
    link: /
  content:
    - text: Home
      link: /
    - text: Honor
      link: /honor
    - Members
    - Join Us
  icon:
    - ':github:'

page:
  index:
    title: V&N Team
    description: An Union CTF Team From China
  honor: ./config/honor.md