navbar:
  title:
    text: :vn(title):V&N Team
    link: /
  content:
    - text: Home
      link: /
    - text: Honor
      link: /honor
    - text: Members
      link: /members
    - Join Us
  icon:
    - icon: ':github:'
      link: https://github.com/Cnily03/vn-website

page:
  index:
    title: V&N Team
    description: An Union CTF Team From China
  honor: ./config/honor.md
  members: ./config/members.yml